# trigger reload
name: Publish Docker image to Docker Hub

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (latest and tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            egk10/htmltopdf:latest
            egk10/htmltopdf:${{ steps.vars.outputs.tag }}

      - name: Image digest
        run: echo "Image digest ${{ steps.docker_build.outputs.digest }}"

# Setup instructions:
# 1. Go to your repo Settings > Secrets and variables > Actions
# 2. Add secrets:
#    - DOCKERHUB_USERNAME: your Docker Hub username (egk10)
#    - DOCKERHUB_TOKEN: a Docker Hub access token or your password (recommended: use a token)
# 3. Create a GitHub Release or push a tag (e.g. v1.0.0) to trigger this workflow.
